// ignore_for_file: avoid_print
/// Generates lib/data/local/migrations/schemas/schema_v1.json by opening an
/// in-memory AppDatabase (no Flutter UI layer needed) and dumping CREATE TABLE
/// statements from sqlite_master.
///
/// Run with: flutter test tool/generate_schema_v1.dart
///
/// This is a workaround for the drift_dev 2.34.0 / drift 2.34.2 schema dump
/// incompatibility (drift 2.34.2 introduced the drift3_preview `schema` getter
/// while drift_dev 2.34.0 still uses the old `allSchemaEntities` API).
library;

import 'dart:convert';
import 'dart:io';

import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:co2diet/data/local/app_database.dart';

void main() {
  test('generate schema_v1.json', () async {
    // Open an in-memory database to get the CREATE TABLE statements.
    // Use the base constructor directly to avoid drift_flutter dependency.
    final db = AppDatabase(NativeDatabase.memory());

    try {
      // Force DB to open and run migrations (creates all tables).
      await db.userProfileDao.getProfile();

      // Query sqlite_master for all CREATE TABLE and CREATE INDEX statements.
      final rows = await db
          .customSelect(
            "SELECT type, name, sql FROM sqlite_master "
            "WHERE type IN ('table', 'index') "
            "AND name NOT LIKE 'sqlite_%' "
            "ORDER BY name;",
          )
          .get();

      final entities = rows
          .where((r) => r.data['sql'] != null)
          .map(
            (r) => {
              'type': r.data['type'] as String,
              'name': r.data['name'] as String,
              'sql': r.data['sql'] as String,
            },
          )
          .toList();

      final schema = {
        '_meta': {
          'description': 'Schema snapshot for drift migration testing. '
              'Generated by tool/generate_schema_v1.dart.',
          'version': '1',
          'drift_version': '2.34.2',
          'schema_version': 1,
          'generated': DateTime.now().toUtc().toIso8601String(),
        },
        'schema_version': 1,
        'entities': entities,
      };

      final outputFile = File(
        'lib/data/local/migrations/schemas/schema_v1.json',
      );
      await outputFile.writeAsString(
        const JsonEncoder.withIndent('  ').convert(schema),
      );

      print('schema_v1.json written to ${outputFile.path}');
      for (final e in entities) {
        print('  ${e['type']}: ${e['name']}');
      }

      expect(entities, isNotEmpty);
    } finally {
      await db.close();
    }
  });
}
